/*
Copyright 2016 James DeFelice

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package io

import (
	"encoding/binary"
	"io"
)

// RecordIO returns a stream that writes log messages to the underlying stream, each
// message prefixed with length bytes generated by binary.PutUvarint.
func RecordIO(delegate io.Writer) Stream {
	var sz [binary.MaxVarintLen64]byte
	return &BufferedStream{
		EOMFunc: func(buf Buffer, err error) error {
			if err != nil {
				return err
			}

			// encode and write the length bytes
			buflen := buf.Len()
			n := binary.PutUvarint(sz[:], uint64(buflen))
			w, err := delegate.Write(sz[:n])
			if err != nil {
				return err
			}
			if w != n {
				// should never happen..
				return io.ErrShortWrite
			}

			// write the data bytes
			written, err := buf.WriteTo(delegate)
			if err != nil {
				return err
			}
			if written != int64(buflen) {
				// should never happen
				return io.ErrShortWrite
			}
			return nil
		},
	}
}
